### PR TITLE
Fail build in case of error with warning, closes #28

### LINKED ISSUE #28: Better handling of errors
So far we can get templates-related errors in two cases:

1. When we've launched `watch` task, which recompiles templates on changes, and non of templates had errors. But during`watch` task we've introduced error.
2. When we launch whole task (let's say, `grunt test`) and one of templates contains error

In first case, Task's behaviour will be according to expected — it will `grunt.log.error(err)` and stop compilation of template until we'll fix error

In second case Task will behave not according to Grunt guidelines: if any template has error, Task will `grunt.log.error(err)` and _continue_ compilation. Do you see problem here? Failed to compile templates means that some pages won't be generated, but in same time we won't receive failed build. It is especially crucial for deployment, since during deploy it will emit error only in log, and won't fail whole build (while should, since we won't receive failed to compile page on production).

Instead it have to do `grunt.fail.warn('Something went wrong')` right after `grunt.log.error(err)` or throw only `grunt.fail.warn(err)` (depending on your preference of colors).

In other words, Task have to throw an warning, which will fail task, but in same time will allow to use `--force` when we want ignore that error. We're using `grunt.fail.warn` here istead of `grunt.fail.fatal`, since it isn't fatal error and we can continue to go on when needed.

In fact, in first case Task should throw `grunt.fail.warn(...)` too, but due to nature of Grunt, Task will be stopped due to error anyway, but it won't happen in second case.

Also note, that due to changes, introduced in `0.3.2`, if one of templates will fail, whole task will fail due to `Fatal error: callback was already called`. It shouldn't happen — it should fail because of `grunt.fail.warn(...)`, error from compilation, but not from error from `async`, otherwise we won't be able to use `--force` to compile all templates despite present error.

### PR DESCRIPTION
**Pull request by ArmorDarks**

### CODE REVIEW

File: tasks/nunjucks.js [hunk 1]
```diff
@@ -48,6 +48,7 @@ module.exports = function(grunt) {
             env.renderString(template, data, function(err, res) {
                 if (err) {
                     grunt.log.error(err);
+                    grunt.fail.warn('Faild to compile one of sources.');
```
Comment (vitkarpov) [inline tasks/nunjucks.js]: there's a typo: fail **e** d to compile one of the sources

**Comment by vitkarpov** [comment]
:+1: I'll merge and fix the typo

File: tasks/nunjucks.js (hunk 1 above)
Comment (ArmorDarks) [inline tasks/nunjucks.js]: oops :) thanks!
